/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2026-02-03 15:23:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "NavClient.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Meet Our Team</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("  background: linear-gradient(135deg, #74ebd5, #9face6);\r\n");
      out.write("  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes popOut {\r\n");
      out.write("  from {\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    transform: translateY(30px) scale(0.95);\r\n");
      out.write("  }\r\n");
      out.write("  to {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    transform: translateY(0) scale(1);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  animation: popOut 0.8s ease-out forwards;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin: 30px 0;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Team Card */\r\n");
      out.write(".team-card {\r\n");
      out.write("  background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("  backdrop-filter: blur(10px);\r\n");
      out.write("  border-radius: 18px;\r\n");
      out.write("  padding: 22px 18px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  max-width: 230px;\r\n");
      out.write("  transition: all 0.35s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-card:hover {\r\n");
      out.write("  transform: translateY(-12px) scale(1.08);\r\n");
      out.write("  box-shadow: 0 18px 35px rgba(0, 0, 0, 0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profile Image */\r\n");
      out.write(".team-card img.rounded-circle {\r\n");
      out.write("  width: 140px;\r\n");
      out.write("  height: 140px;\r\n");
      out.write("  object-fit: cover;\r\n");
      out.write("  border: 4px solid #2193b0;\r\n");
      out.write("  transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-card:hover img {\r\n");
      out.write("  transform: rotate(2deg) scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Name */\r\n");
      out.write(".team-card h5 {\r\n");
      out.write("  margin-top: 14px;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Role */\r\n");
      out.write(".team-card p {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  margin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Social Icons */\r\n");
      out.write(".social-icons {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  gap: 18px;\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons img {\r\n");
      out.write("  width: 32px;\r\n");
      out.write("  height: 32px;\r\n");
      out.write("  transition: transform 0.3s ease, filter 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons img:hover {\r\n");
      out.write("  transform: scale(1.25);\r\n");
      out.write("  filter: drop-shadow(0 4px 6px rgba(0,0,0,0.3));\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h2>✨ Meet Our Team ✨</h2>\r\n");
      out.write("\r\n");
      out.write("  <!-- 5 cards in one row -->\r\n");
      out.write("  <div class=\"row row-cols-lg-5 row-cols-md-3 row-cols-sm-2 row-cols-1 g-4 justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Card 1 -->\r\n");
      out.write("    <div class=\"col d-flex justify-content-center\">\r\n");
      out.write("      <div class=\"team-card text-center\">\r\n");
      out.write("        <img src=\"Images/Soubhagya_Kabiraj.jpg\" class=\"rounded-circle mb-3\" alt=\"Soubhagya Kabiraj\">\r\n");
      out.write("        <h5>Soubhagya Kabiraj</h5>\r\n");
      out.write("        <p class=\"text-muted\">Full Stack Developer</p>\r\n");
      out.write("        <div class=\"social-icons\">\r\n");
      out.write("          <a href=\"https://www.linkedin.com/in/soubhagya-kabiraj-a0069228b/\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://github.com/Soubhagya-Kabiraj\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg\">\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Card 2 -->\r\n");
      out.write("    <div class=\"col d-flex justify-content-center\">\r\n");
      out.write("      <div class=\"team-card text-center\">\r\n");
      out.write("        <img src=\"Images/Sourav.jpg\" class=\"rounded-circle mb-3\" alt=\"Sourav Gorain\">\r\n");
      out.write("        <h5>Sourav Gorain</h5>\r\n");
      out.write("        <p class=\"text-muted\">Frontend UI Designer</p>\r\n");
      out.write("        <div class=\"social-icons\">\r\n");
      out.write("          <a href=\"https://www.linkedin.com/in/souravgorain/\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://github.com/SouravGorain73\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg\">\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Card 3 -->\r\n");
      out.write("    <div class=\"col d-flex justify-content-center\">\r\n");
      out.write("      <div class=\"team-card text-center\">\r\n");
      out.write("        <img src=\"Images/Khushbu.jpg\" class=\"rounded-circle mb-3\" alt=\"Khushbu Singh\">\r\n");
      out.write("        <h5>Khushbu Singh</h5>\r\n");
      out.write("        <p class=\"text-muted\">Database Designer</p>\r\n");
      out.write("        <div class=\"social-icons\">\r\n");
      out.write("          <a href=\"https://www.linkedin.com/in/khushbu-singh-a366a32a0/\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://github.com/khushu2608\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg\">\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Card 4 -->\r\n");
      out.write("    <div class=\"col d-flex justify-content-center\">\r\n");
      out.write("      <div class=\"team-card text-center\">\r\n");
      out.write("        <img src=\"Images/Shreyashree.jpeg\" class=\"rounded-circle mb-3\" alt=\"Shreyashree Banerjee\">\r\n");
      out.write("        <h5>Shreyashree Banerjee</h5>\r\n");
      out.write("        <p class=\"text-muted\">Frontend Developer</p>\r\n");
      out.write("        <div class=\"social-icons\">\r\n");
      out.write("          <a href=\"https://www.linkedin.com/in/shreyashree-banerjee-61bb88290\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://github.com/ShreyashreeRUKE\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg\">\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Card 5 -->\r\n");
      out.write("    <div class=\"col d-flex justify-content-center\">\r\n");
      out.write("      <div class=\"team-card text-center\">\r\n");
      out.write("        <img src=\"Images/Shreya.jpeg\" class=\"rounded-circle mb-3\" alt=\"Shreya Show\">\r\n");
      out.write("        <h5>Shreya Show</h5>\r\n");
      out.write("        <p class=\"text-muted\">Frontend Developer</p>\r\n");
      out.write("        <div class=\"social-icons\">\r\n");
      out.write("          <a href=\"https://www.linkedin.com/in/shreya-kumari-show-b98248279\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://github.com/SHREYASHOW\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg\">\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
