/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-09-12 14:26:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import master.dao.BookTicketDao;

public final class BookingDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("master.dao.BookTicketDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Ticket History</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background: linear-gradient(135deg, #74ebd5, #9face6);\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    .ticket-card {\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        transition: all 0.3s ease-in-out;\r\n");
      out.write("        width: 95%;         \r\n");
      out.write("    	max-width: 1600px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top:20px;\r\n");
      out.write("    }\r\n");
      out.write("    .ticket-card:hover {\r\n");
      out.write("        transform: scale(1.01);\r\n");
      out.write("        box-shadow: 0 12px 28px rgba(0,0,0,0.25);\r\n");
      out.write("    }\r\n");
      out.write("    .ticket-header {\r\n");
      out.write("        background: linear-gradient(135deg, #2575fc, #6a11cb);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .ticket-header h2 {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: 1.8rem;\r\n");
      out.write("        letter-spacing: 1px;\r\n");
      out.write("    }\r\n");
      out.write("    .ticket-table {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    .ticket-table th {\r\n");
      out.write("        background: #f1f5f9;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .ticket-table td {\r\n");
      out.write("        background: #ffffff;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("    .highlight {\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .badge-custom {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        padding: 8px 14px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-btn {\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding: 10px 25px;\r\n");
      out.write("    }\r\n");
      out.write("    .btn{\r\n");
      out.write("        margin-top:20px;\r\n");
      out.write("        background: linear-gradient(135deg, #2575fc, #6a11cb);\r\n");
      out.write("    }  \r\n");
      out.write("    .card{\r\n");
      out.write("    width:90%;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"card ticket-card shadow-lg\">\r\n");
      out.write("        <div class=\"ticket-header\">\r\n");
      out.write("            <h2>🎟️ Booking Details</h2>\r\n");
      out.write("            <p class=\"mb-0\">All the bookings with <strong>Train Ease</strong></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            ");
                
                BookTicketDao dao = new BookTicketDao();
                ResultSet rs = dao.getTickets();
            
      out.write("\r\n");
      out.write("            <table class=\"table ticket-table table-bordered text-center\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Ticket ID</th>\r\n");
      out.write("                        <th>Train No</th>\r\n");
      out.write("                        <th>Train Name</th>\r\n");
      out.write("                        <th>From</th>\r\n");
      out.write("                        <th>To</th>\r\n");
      out.write("                        <th>Passenger</th>\r\n");
      out.write("                        <th>Age</th>\r\n");
      out.write("                        <th>Gender</th>\r\n");
      out.write("                        <th>Fare</th>\r\n");
      out.write("                        <th>Booking Date</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                        boolean hasData = false;
                        while(rs != null && rs.next()) {
                            hasData = true;
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"highlight text-primary\">");
      out.print( rs.getInt("TICKET_ID") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getString("TRAIN_NO") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getString("TRAIN_NAME") );
      out.write("</td>\r\n");
      out.write("                        <td><span class=\"badge bg-success badge-custom\">");
      out.print( rs.getString("FROM_STATION") );
      out.write("</span></td>\r\n");
      out.write("                        <td><span class=\"badge bg-danger badge-custom\">");
      out.print( rs.getString("TO_STATION") );
      out.write("</span></td>\r\n");
      out.write("                        <td>");
      out.print( rs.getString("PASSENGER_NAME") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getInt("AGE") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getString("GENDER") );
      out.write("</td>\r\n");
      out.write("                        <td class=\"text-success fw-bold\">₹ ");
      out.print( rs.getDouble("FARE") );
      out.write("</td>\r\n");
      out.write("                        <td class=\"fw-bold\">");
      out.print( rs.getTimestamp("BOOKING_DATE") );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
 } if(!hasData) { 
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"10\" class=\"text-danger fw-bold\">No tickets found </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-footer text-center\">\r\n");
      out.write("            <a href=\"NavAdmin.jsp\" class=\"btn btn-primary footer-btn\">⬅ Back to Menu</a>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
