/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-09-27 13:25:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BookTicket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BOOK TICKET</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    background: linear-gradient(135deg, #74ebd5, #9face6 );\r\n");
      out.write("    font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("    min-height: 100vh;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".card {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 650px;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    box-shadow: 0 8px 24px rgba(0,0,0,0.25);\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("}\r\n");
      out.write(".card-header {\r\n");
      out.write("    background: linear-gradient(135deg, #007bff, #00c6ff);\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".card-body {\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("}\r\n");
      out.write(".form-control {\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    padding-left: 40px;\r\n");
      out.write("}\r\n");
      out.write(".input-group-text {\r\n");
      out.write("    border-radius: 12px 0 0 12px;\r\n");
      out.write("    background-color: #f0f0f0;\r\n");
      out.write("}\r\n");
      out.write(".btn-custom {\r\n");
      out.write("    background: linear-gradient(135deg, #007bff, #00c6ff);\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    font-size: 1.1rem;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".btn-custom:hover {\r\n");
      out.write("    background: linear-gradient(135deg, #0056b3, #0096c7);\r\n");
      out.write("    transform: scale(1.02);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\">\r\n");
      out.write("        🎟️ Book Your Train Ticket\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("        <form action=\"BookTicketServe\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Train Number -->\r\n");
      out.write("            <div class=\"input-group mb-3\">\r\n");
      out.write("                <span class=\"input-group-text\"><i class=\"bi bi-train-front\"></i></span>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"trainNo\" placeholder=\"Train Number\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Train Name -->\r\n");
      out.write("            <div class=\"input-group mb-3\">\r\n");
      out.write("                <span class=\"input-group-text\"><i class=\"bi bi-card-text\"></i></span>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"trainName\" placeholder=\"Train Name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- From Station -->\r\n");
      out.write("            <div class=\"input-group mb-3\">\r\n");
      out.write("                <span class=\"input-group-text\"><i class=\"bi bi-geo-alt\"></i></span>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"fromStation\" placeholder=\"From Station\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- To Station -->\r\n");
      out.write("            <div class=\"input-group mb-3\">\r\n");
      out.write("                <span class=\"input-group-text\"><i class=\"bi bi-geo\"></i></span>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"toStation\" placeholder=\"To Station\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Passenger Name -->\r\n");
      out.write("            <div class=\"input-group mb-3\">\r\n");
      out.write("                <span class=\"input-group-text\"><i class=\"bi bi-person\"></i></span>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"pname\" placeholder=\"Passenger Name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Age -->\r\n");
      out.write("            <div class=\"input-group mb-3\">\r\n");
      out.write("                <span class=\"input-group-text\"><i class=\"bi bi-calendar\"></i></span>\r\n");
      out.write("                <input type=\"number\" class=\"form-control\" name=\"age\" placeholder=\"Age\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Gender -->\r\n");
      out.write("            <div class=\"input-group mb-4\">\r\n");
      out.write("                <span class=\"input-group-text\"><i class=\"bi bi-gender-ambiguous\"></i></span>\r\n");
      out.write("                <select class=\"form-control\" name=\"gender\" required>\r\n");
      out.write("                    <option value=\"\">Select Gender</option>\r\n");
      out.write("                    <option>Male</option>\r\n");
      out.write("                    <option>Female</option>\r\n");
      out.write("                    <option>Other</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Submit -->\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-custom w-100\">Book Ticket ✅</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
