/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-09-07 14:05:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>HOME PAGE</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background: url('https://th.bing.com/th/id/R.23749078a5e09832cca2a7cd006e30c2?rik=z0OvNE0KxhgxaA&riu=http%3a%2f%2fimages.fineartamerica.com%2fimages%2fartworkimages%2fmediumlarge%2f1%2ftrains-irm-collage-blue-background-horizontal-thomas-woolworth.jpg&ehk=%2bkEROeQ70dUmXP2QF8VzzobINS%2f92vMssKuS7DhBt6c%3d&risl=&pid=ImgRaw&r=0') no-repeat center center fixed;\r\n");
      out.write("        background-size: cover;        \r\n");
      out.write("        font-family: \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    body::before {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: rgba(10, 10, 10, 0.8); \r\n");
      out.write("        z-index: -1;\r\n");
      out.write("    }\r\n");
      out.write("    #title {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 42px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: white;\r\n");
      out.write("        background: linear-gradient(90deg, #0d6efd, #20c997);\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        margin: 20px auto;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        box-shadow: 0 5px 20px rgba(0,0,0,0.4);\r\n");
      out.write("    }\r\n");
      out.write("    #main {\r\n");
      out.write("        width: 35%;\r\n");
      out.write("        margin: 20px auto;        \r\n");
      out.write("        text-align: center;               \r\n");
      out.write("        background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("        backdrop-filter: blur(18px);\r\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        border-radius: 18px;  \r\n");
      out.write("        box-shadow: 0 8px 25px rgba(0,0,0,0.4);\r\n");
      out.write("        animation: fadeIn 1s ease-out;\r\n");
      out.write("    }\r\n");
      out.write("    #main h2 {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #0d6efd;\r\n");
      out.write("        margin-bottom: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    input.form-control {\r\n");
      out.write("        margin: 12px auto;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        width: 85%;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        box-shadow: 0 3px 10px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .btn {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("        margin-top: 12px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .btn:hover {\r\n");
      out.write("        transform: scale(1.05);\r\n");
      out.write("        box-shadow: 0 6px 15px rgba(0,0,0,0.25);\r\n");
      out.write("    }\r\n");
      out.write("    #reg-btn {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("        from {opacity: 0; transform: translateY(-30px);}\r\n");
      out.write("        to {opacity: 1; transform: translateY(0);}\r\n");
      out.write("    }\r\n");
      out.write("</style> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"title\">RAILWAY TICKET BOOKING APP</div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("      <form action=\"LoginServe\" method=\"post\">\r\n");
      out.write("        <h2>LOGIN TO TRAIN EASE</h2>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"uname\" placeholder=\"Enter Username\">\r\n");
      out.write("        <input type=\"password\" class=\"form-control\" name=\"pass\" placeholder=\"Enter Password\">\r\n");
      out.write("        \r\n");
      out.write("        <button class=\"btn btn-outline-info\" type=\"submit\">LOGIN</button>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div id=\"reg-btn\">\r\n");
      out.write("          <a href=\"Register.jsp\" class=\"btn btn-success fw-bold\">CREATE NEW ACCOUNT</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
